use super::{normalize_common_lisp_operator_head, CommonLispOperator};

pub(super) fn common_lisp_operator_from_head(head: &str) -> Option<CommonLispOperator> {
    let normalized_head = normalize_common_lisp_operator_head(head).to_ascii_lowercase();
    Some(match normalized_head.as_str() {
        "let" => CommonLispOperator::Let,
        "let*" => CommonLispOperator::LetStar,
        "symbol-macrolet" | "cl-symbol-macrolet" => CommonLispOperator::SymbolMacrolet,
        "destructuring-bind" => CommonLispOperator::DestructuringBind,
        "multiple-value-bind" => CommonLispOperator::MultipleValueBind,
        "handler-case" => CommonLispOperator::HandlerCase,
        "restart-case" => CommonLispOperator::RestartCase,
        "handler-bind" => CommonLispOperator::HandlerBind,
        "restart-bind" => CommonLispOperator::RestartBind,
        "dolist" => CommonLispOperator::Dolist,
        "dotimes" => CommonLispOperator::Dotimes,
        "do" => CommonLispOperator::Do,
        "do*" => CommonLispOperator::DoStar,
        "prog" => CommonLispOperator::Prog,
        "prog*" => CommonLispOperator::ProgStar,
        "with-slots" => CommonLispOperator::WithSlots,
        "with-accessors" => CommonLispOperator::WithAccessors,
        "with-open-file" => CommonLispOperator::WithOpenFile,
        "with-open-stream" => CommonLispOperator::WithOpenStream,
        "with-input-from-string" => CommonLispOperator::WithInputFromString,
        "with-output-to-string" => CommonLispOperator::WithOutputToString,
        "lambda" => CommonLispOperator::Lambda,
        "fn" => CommonLispOperator::Fn,
        "defun" => CommonLispOperator::Defun,
        "defmacro" => CommonLispOperator::Defmacro,
        "defgeneric" => CommonLispOperator::Defgeneric,
        "define-method-combination" => CommonLispOperator::DefineMethodCombination,
        "defmethod" => CommonLispOperator::Defmethod,
        "cl-defmethod" => CommonLispOperator::ClDefmethod,
        "defclass" => CommonLispOperator::Defclass,
        "defstruct" => CommonLispOperator::Defstruct,
        "deftype" => CommonLispOperator::Deftype,
        "define-condition" => CommonLispOperator::DefineCondition,
        "defvar" => CommonLispOperator::Defvar,
        "defglobal" => CommonLispOperator::Defglobal,
        "define-symbol-macro" => CommonLispOperator::DefineSymbolMacro,
        "defconstant" => CommonLispOperator::Defconstant,
        "defparameter" => CommonLispOperator::Defparameter,
        "defpackage" => CommonLispOperator::Defpackage,
        "in-package" => CommonLispOperator::InPackage,
        "provide" => CommonLispOperator::Provide,
        "require" => CommonLispOperator::Require,
        "load" => CommonLispOperator::Load,
        "load-file" => CommonLispOperator::LoadFile,
        "load-library" => CommonLispOperator::LoadLibrary,
        "use-package" => CommonLispOperator::UsePackage,
        "import" => CommonLispOperator::Import,
        "asdf:defsystem" | "defsystem" => CommonLispOperator::Defsystem,
        "define-setf-expander" => CommonLispOperator::DefineSetfExpander,
        "define-compiler-macro" => CommonLispOperator::DefineCompilerMacro,
        "define-modify-macro" => CommonLispOperator::DefineModifyMacro,
        "defsetf" => CommonLispOperator::Defsetf,
        "locally" => CommonLispOperator::Locally,
        "flet" | "cl-flet" => CommonLispOperator::Flet,
        "labels" | "cl-labels" => CommonLispOperator::Labels,
        "macrolet" | "cl-macrolet" => CommonLispOperator::Macrolet,
        "compiler-macrolet" => CommonLispOperator::CompilerMacrolet,
        "loop" => CommonLispOperator::Loop,
        _ => return None,
    })
}
