//! Machine-readable catalog of the whole CLI surface, generated by walking
//! the clap command tree so it can never drift from the real interface.

use anyhow::Result;
use clap::builder::Command as ClapCommand;
use clap::{Arg, ArgAction, Args, CommandFactory, ValueEnum};
use serde_json::{Value, json};

use super::args::OutputFormat;

#[derive(Clone, Copy, Debug, ValueEnum)]
enum CapabilitiesSchemaVersion {
    #[value(name = "1")]
    V1,
    #[value(name = "2")]
    V2,
}

impl CapabilitiesSchemaVersion {
    const fn number(self) -> u8 {
        match self {
            Self::V1 => 1,
            Self::V2 => 2,
        }
    }
}

#[derive(Debug, Args)]
pub(super) struct CapabilitiesArgs {
    /// Output format. Defaults to json: this command exists for agent discovery.
    #[arg(long, value_enum, default_value_t = OutputFormat::Json)]
    pub(super) output: OutputFormat,

    /// Machine-readable schema version.
    #[arg(long, value_enum, default_value = "1")]
    schema_version: CapabilitiesSchemaVersion,
}

pub(super) fn capabilities(args: CapabilitiesArgs) -> Result<()> {
    let root = super::Cli::command();
    match args.output {
        OutputFormat::Json => {
            let mut report = json!({
                "schema_version": args.schema_version.number(),
                "name": root.get_name(),
                "version": root.get_version(),
                "about": about_text(&root),
                "commands": subcommand_reports(&root, args.schema_version),
            });
            if matches!(args.schema_version, CapabilitiesSchemaVersion::V2) {
                report["dialect_contract"] = super::contract::dialect_contract_report();
            }
            println!("{}", serde_json::to_string_pretty(&report)?);
        }
        OutputFormat::Text => {
            let mut lines = Vec::new();
            render_text(&root, &mut Vec::new(), &mut lines);
            println!("{}", lines.join("\n"));
        }
    }
    Ok(())
}

fn subcommand_reports(
    command: &ClapCommand,
    schema_version: CapabilitiesSchemaVersion,
) -> Vec<Value> {
    command
        .get_subcommands()
        .filter(|subcommand| subcommand.get_name() != "help")
        .map(|subcommand| {
            let nested = subcommand_reports(subcommand, schema_version);
            let mut report = json!({
                "name": subcommand.get_name(),
                "about": about_text(subcommand),
                "args": argument_reports(subcommand, schema_version),
            });
            if !nested.is_empty() {
                report["commands"] = Value::Array(nested);
            }
            report
        })
        .collect()
}

fn argument_reports(
    command: &ClapCommand,
    schema_version: CapabilitiesSchemaVersion,
) -> Vec<Value> {
    command
        .get_arguments()
        .filter(|arg| {
            !matches!(
                (arg.get_id().as_str(), schema_version),
                ("help" | "version", _) | ("schema_version", CapabilitiesSchemaVersion::V1)
            )
        })
        .map(|arg| {
            json!({
                "id": arg.get_id().as_str(),
                "long": arg.get_long(),
                "short": arg.get_short().map(String::from),
                "kind": argument_kind(arg),
                "help": arg.get_help().map(ToString::to_string),
                "required": arg.is_required_set(),
                "repeatable": is_repeatable(arg),
                "value_names": arg
                    .get_value_names()
                    .map(|names| names.iter().map(ToString::to_string).collect::<Vec<_>>()),
                "default_values": default_values(arg),
                "possible_values": possible_values(arg),
            })
        })
        .collect()
}

fn argument_kind(arg: &Arg) -> &'static str {
    if arg.is_positional() {
        "positional"
    } else if takes_value(arg) {
        "option"
    } else {
        "flag"
    }
}

fn takes_value(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Set | ArgAction::Append)
}

fn is_repeatable(arg: &Arg) -> bool {
    matches!(arg.get_action(), ArgAction::Append | ArgAction::Count)
        || arg
            .get_num_args()
            .is_some_and(|range| range.max_values() > 1)
}

fn default_values(arg: &Arg) -> Vec<String> {
    arg.get_default_values()
        .iter()
        .map(|value| value.to_string_lossy().into_owned())
        .collect()
}

fn possible_values(arg: &Arg) -> Option<Vec<String>> {
    let values = arg
        .get_possible_values()
        .iter()
        .map(|value| value.get_name().to_owned())
        .collect::<Vec<_>>();
    (!values.is_empty()).then_some(values)
}

fn about_text(command: &ClapCommand) -> Option<String> {
    command.get_about().map(ToString::to_string)
}

fn render_text(command: &ClapCommand, prefix: &mut Vec<String>, lines: &mut Vec<String>) {
    for subcommand in command.get_subcommands() {
        if subcommand.get_name() == "help" {
            continue;
        }

        prefix.push(subcommand.get_name().to_owned());
        let about = about_text(subcommand).unwrap_or_default();
        lines.push(format!("paredit {}  {}", prefix.join(" "), about));
        for arg in subcommand.get_arguments() {
            if matches!(arg.get_id().as_str(), "help" | "version") {
                continue;
            }
            lines.push(format!("  {}", render_arg(arg)));
        }
        render_text(subcommand, prefix, lines);
        prefix.pop();
    }
}

fn render_arg(arg: &Arg) -> String {
    let name = match (arg.get_long(), arg.is_positional()) {
        (Some(long), _) => format!("--{long}"),
        (None, true) => format!("<{}>", arg.get_id().as_str().to_uppercase()),
        (None, false) => arg.get_id().to_string(),
    };
    let value = if takes_value(arg) {
        arg.get_value_names()
            .and_then(|names| names.first().map(|value_name| format!(" <{value_name}>")))
            .unwrap_or_else(|| " <VALUE>".to_owned())
    } else {
        String::new()
    };
    let help = arg
        .get_help()
        .map(|help| format!("  {help}"))
        .unwrap_or_default();
    format!("{name}{value}{help}")
}
